services:
    netgen_layouts.view.view_renderer:
        class: Netgen\Layouts\View\ViewRenderer
        arguments:
            - "@event_dispatcher"
            - "@twig"

    netgen_layouts.view.view_builder:
        class: Netgen\Layouts\View\ViewBuilder
        arguments:
            - "@netgen_layouts.view.template_resolver"
            - "@event_dispatcher"
            - !tagged_iterator netgen_layouts.view_provider

    netgen_layouts.view.renderer:
        class: Netgen\Layouts\View\Renderer
        arguments:
            - "@netgen_layouts.view.view_builder"
            - "@netgen_layouts.view.view_renderer"

    netgen_layouts.view.template_resolver:
        class: Netgen\Layouts\View\TemplateResolver
        arguments:
            - "@netgen_layouts.configuration"
            - !abstract "Set in TemplateResolverPass"
