view:
    form_view:
        api:
            layout\create:
                template: "@NetgenBlockManagerAdmin/app/form/layout/create.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Form\CreateType
            layout\edit:
                template: "@NetgenBlockManagerAdmin/app/form/layout/edit.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Form\EditType
            block\full_edit:
                template: "@NetgenBlockManagerAdmin/app/form/block/edit/full.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\FullEditType
            block\content_edit:
                template: "@NetgenBlockManagerAdmin/app/form/block/edit/content.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\ContentEditType
            block\design_edit:
                template: "@NetgenBlockManagerAdmin/app/form/block/edit/design.html.twig"
                match:
                    form\type: Netgen\BlockManager\Block\Form\DesignEditType
            collection\full_edit:
                template: "@NetgenBlockManagerAdmin/app/form/collection/edit/full.html.twig"
                match:
                    form\type: Netgen\BlockManager\Collection\Form\CollectionEditType
            query\full_edit:
                template: "@NetgenBlockManagerAdmin/app/form/query/edit/full.html.twig"
                match:
                    form\type: Netgen\BlockManager\Collection\Form\QueryEditType
            collection\item\config\visibility\edit:
                template: "@NetgenBlockManagerAdmin/app/form/collection/item/config/edit/visibility.html.twig"
                match:
                    form\type: Netgen\BlockManager\Config\Form\EditType
                    form\config\value_type: Netgen\BlockManager\API\Values\Collection\Item
                    form\config\config_key: visibility
        admin:
            layout\copy:
                template: "@NetgenBlockManagerAdmin/admin/layouts/form/copy_layout.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Form\CopyType
            shared_layout\related_layouts_cache:
                template: "@NetgenBlockManagerAdmin/admin/shared_layouts/form/clear_related_layouts_cache.html.twig"
                match:
                    form\type: Netgen\Bundle\BlockManagerAdminBundle\Form\Admin\Type\ClearLayoutsCacheType
            condition\type:
                template: "@NetgenBlockManagerAdmin/admin/layout_resolver/form/edit_condition_type.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Resolver\Form\ConditionType
            target\type:
                template: "@NetgenBlockManagerAdmin/admin/layout_resolver/form/edit_target_type.html.twig"
                match:
                    form\type: Netgen\BlockManager\Layout\Resolver\Form\TargetType
