parameters:
    netgen_block_manager.block.block_definition.handler.plugin.common.groups: ['design', 'common']

    netgen_block_manager.block.block_definition.handler.plugin.paged_collections.groups: ['design']
    netgen_block_manager.block.block_definition.handler.plugin.paged_collections.pager_types:
        pager: 'Pager'
        load_more: 'Load more'

services:
    netgen_block_manager.block.block_definition_factory:
        class: Netgen\BlockManager\Block\BlockDefinitionFactory
        public: false
        arguments:
            - "@netgen_block_manager.parameters.translatable_parameter_builder_factory"
            - "@netgen_block_manager.block.registry.handler_plugin"
            - "@netgen_block_manager.config.config_definition_factory"
            - "@netgen_block_manager.http_cache.block.cacheable_resolver"

    netgen_block_manager.block.registry.block_definition:
        class: Netgen\BlockManager\Block\Registry\BlockDefinitionRegistry
        public: true
        arguments:
            - []

    netgen_block_manager.block.registry.handler_plugin:
        class: Netgen\BlockManager\Block\Registry\HandlerPluginRegistry
        public: false
        arguments:
            - []

    netgen_block_manager.block.registry.block_type:
        class: Netgen\BlockManager\Block\Registry\BlockTypeRegistry
        public: true
        arguments:
            - []

    netgen_block_manager.block.registry.block_type_group:
        class: Netgen\BlockManager\Block\Registry\BlockTypeGroupRegistry
        public: true
        arguments:
            - []

    # Various block plugins

    netgen_block_manager.block.block_definition.handler.plugin.common:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\CommonParametersPlugin
        public: false
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.plugin.common.groups%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 0 }

    netgen_block_manager.block.block_definition.handler.plugin.paged_collections:
        class: Netgen\BlockManager\Block\BlockDefinition\Handler\PagedCollectionsPlugin
        public: false
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.plugin.paged_collections.pager_types%"
            - "%netgen_block_manager.block.block_definition.handler.plugin.paged_collections.groups%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 10 }
