services:
    netgen_block_manager.config.config_definition_factory:
        class: Netgen\BlockManager\Config\ConfigDefinitionFactory
        public: false
        arguments:
            - "@netgen_block_manager.parameters.parameter_builder_factory"
