services:
    netgen_block_manager.normalizer.value:
        class: Netgen\BlockManager\Serializer\Normalizer\ValueNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.view:
        class: Netgen\BlockManager\Serializer\Normalizer\ViewNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.form_view:
        class: Netgen\BlockManager\Serializer\Normalizer\FormViewNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.exception:
        class: Netgen\BlockManager\Serializer\Normalizer\ExceptionNormalizer
        public: false
        calls:
            - [setOutputDebugInfo, ["%kernel.debug%"]]
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.parameter:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\ParameterNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.placeholder:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\PlaceholderNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_reference:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionReferenceNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\LayoutNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_item:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionItemNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.item.item_loader"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_query:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionQueryNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result_set:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionResultSetNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionResultNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockTypeNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type_group:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockTypeGroupNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout_type:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\LayoutTypeNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }
