services:
    netgen_block_manager.normalizer.base:
        class: Netgen\BlockManager\Serializer\Normalizer
        public: false
        abstract: true
        calls:
            - [setNormalizer, ["@serializer"]]

    netgen_block_manager.normalizer.value:
        class: Netgen\BlockManager\Serializer\Normalizer\ValueNormalizer
        public: false
        parent: netgen_block_manager.normalizer.base
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.exception:
        class: Netgen\BlockManager\Serializer\Normalizer\ExceptionNormalizer
        public: false
        arguments:
            - "%kernel.debug%"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.view:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\ViewNormalizer
        public: false
        parent: netgen_block_manager.normalizer.base
        arguments:
            - "@netgen_block_manager.view.renderer"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.parameter:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\ParameterNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockNormalizer
        public: false
        parent: netgen_block_manager.normalizer.base
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.placeholder:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\PlaceholderNormalizer
        public: false
        parent: netgen_block_manager.normalizer.base
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\LayoutNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_item:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionItemNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.item.url_generator"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_query:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionQueryNormalizer
        public: false
        parent: netgen_block_manager.normalizer.base
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result_set:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionResultSetNormalizer
        public: false
        parent: netgen_block_manager.normalizer.base
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.collection_result:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\CollectionResultNormalizer
        public: false
        arguments:
            - "@netgen_block_manager.item.url_generator"
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockTypeNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.block_type_group:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\BlockTypeGroupNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }

    netgen_block_manager.normalizer.v1.layout_type:
        class: Netgen\BlockManager\Serializer\Normalizer\V1\LayoutTypeNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }
