services:
    netgen_block_manager.param_converter.page.block:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\Page\BlockParamConverter
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.page.zone:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\Page\ZoneParamConverter
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.page.layout:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\Page\LayoutParamConverter
        arguments:
            - "@netgen_block_manager.api.service.layout"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.page.collection_reference:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\Page\CollectionReferenceParamConverter
        arguments:
            - "@netgen_block_manager.api.service.block"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.collection.collection:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\Collection\CollectionParamConverter
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.collection.item:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\Collection\ItemParamConverter
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.collection.query:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\Collection\QueryParamConverter
        arguments:
            - "@netgen_block_manager.api.service.collection"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.layout_resolver.rule:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\LayoutResolver\RuleParamConverter
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.layout_resolver.condition:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\LayoutResolver\ConditionParamConverter
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
        tags:
            - { name: request.param_converter, priority: 0 }

    netgen_block_manager.param_converter.layout_resolver.target:
        class: Netgen\Bundle\BlockManagerBundle\ParamConverter\LayoutResolver\TargetParamConverter
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
        tags:
            - { name: request.param_converter, priority: 0 }
