parameters:
    netgen_block_manager.controller.block_controller: "ngbm_block"

services:
    netgen_block_manager.templating.twig.runtime.container_loader:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\Loader\ContainerRuntimeLoader
        public: false
        arguments:
            - "@service_container"

    netgen_block_manager.templating.global_variable:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\GlobalVariable
        public: false
        arguments:
            - "@netgen_block_manager.configuration"
            - "@netgen_block_manager.layout.resolver"
            - "@netgen_block_manager.templating.pagelayout_resolver"
            - "@netgen_block_manager.view.view_builder"
            - "@request_stack"
            - "%netgen_block_manager.debug%"

    netgen_block_manager.templating.twig.extension.rendering:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\RenderingExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.rendering:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\RenderingRuntime
        # public: false
        arguments:
            - "@netgen_block_manager.api.service.block"
            - "@netgen_block_manager.view.renderer.fragment"
            - "@netgen_block_manager.locale.provider"
            - "@request_stack"
            - "@netgen_block_manager.error.handler"
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }

    netgen_block_manager.templating.twig.extension.collection_pager:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\CollectionPagerExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.collection_pager:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\CollectionPagerRuntime
        # public: false
        arguments:
            - "@netgen_block_manager.templating.twig.runtime.collection_pager.route_generator"
            - "@netgen_block_manager.collection.result.pagerfanta.view"
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }

    netgen_block_manager.templating.twig.runtime.collection_pager.route_generator:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\CollectionPager\RouteGenerator
        public: false
        arguments:
            - "@netgen_block_manager.context"
            - "@uri_signer"
            - "@router"

    netgen_block_manager.templating.twig.extension.item:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\ItemExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.item:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\ItemRuntime
        # public: false
        arguments:
            - "@netgen_block_manager.item.item_loader"
            - "@netgen_block_manager.item.url_generator"
            - "@netgen_block_manager.error.handler"
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }

    netgen_block_manager.templating.twig.extension.helpers:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Extension\HelpersExtension
        public: false
        tags:
            - { name: twig.extension }

    netgen_block_manager.templating.twig.runtime.helpers:
        class: Netgen\Bundle\BlockManagerBundle\Templating\Twig\Runtime\HelpersRuntime
        # public: false
        tags:
            - { name: twig.runtime }
            - { name: netgen_block_manager.twig.runtime }

    netgen_block_manager.templating.pagelayout_resolver.default:
        class: Netgen\Bundle\BlockManagerBundle\Templating\PageLayoutResolver
        public: false
        arguments:
            - "%netgen_block_manager.pagelayout%"

    netgen_block_manager.templating.pagelayout_resolver:
        alias: netgen_block_manager.templating.pagelayout_resolver.default
        public: false
