services:
    netgen_layouts.layout.resolver.condition_type.route_parameter:
        class: Netgen\Layouts\Layout\Resolver\ConditionType\RouteParameter
        tags:
            - { name: netgen_layouts.condition_type }

    netgen_layouts.layout.resolver.condition_type.query_parameter:
        class: Netgen\Layouts\Layout\Resolver\ConditionType\QueryParameter
        tags:
            - { name: netgen_layouts.condition_type }

    netgen_layouts.layout.resolver.condition_type.exception:
        class: Netgen\Layouts\Layout\Resolver\ConditionType\Exception
        tags:
            - { name: netgen_layouts.condition_type }

    netgen_layouts.layout.resolver.condition_type.time:
        class: Netgen\Layouts\Layout\Resolver\ConditionType\Time
        tags:
            - { name: netgen_layouts.condition_type }
