services:
    netgen_block_manager.view.matcher.api_version:
        class: Netgen\BlockManager\View\Matcher\APIVersion
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: api_version }

    netgen_block_manager.view.matcher.form.type:
        class: Netgen\BlockManager\View\Matcher\Form\Type
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\type }

    netgen_block_manager.view.matcher.form.block.definition:
        class: Netgen\BlockManager\View\Matcher\Form\Block\Definition
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\block\definition }

    netgen_block_manager.view.matcher.form.query.type:
        class: Netgen\BlockManager\View\Matcher\Form\Query\Type
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\query\type }

    netgen_block_manager.view.matcher.form.config.config_key:
        class: Netgen\BlockManager\View\Matcher\Form\Config\ConfigKey
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\config\config_key }

    netgen_block_manager.view.matcher.form.config.value_type:
        class: Netgen\BlockManager\View\Matcher\Form\Config\ValueType
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: form\config\value_type }

    netgen_block_manager.view.matcher.parameter.type:
        class: Netgen\BlockManager\View\Matcher\Parameter\Type
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: parameter\type }

    netgen_block_manager.view.matcher.layout.type:
        class: Netgen\BlockManager\View\Matcher\Layout\Type
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: layout\type }

    netgen_block_manager.view.matcher.layout.shared:
        class: Netgen\BlockManager\View\Matcher\Layout\Shared
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: layout\shared }

    netgen_block_manager.view.matcher.block.definition:
        class: Netgen\BlockManager\View\Matcher\Block\Definition
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: block\definition }

    netgen_block_manager.view.matcher.block.view_type:
        class: Netgen\BlockManager\View\Matcher\Block\ViewType
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: block\view_type }

    netgen_block_manager.view.matcher.item.view_type:
        class: Netgen\BlockManager\View\Matcher\Item\ViewType
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: item\view_type }

    netgen_block_manager.view.matcher.item.value_type:
        class: Netgen\BlockManager\View\Matcher\Item\ValueType
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: item\value_type }

    netgen_block_manager.view.matcher.rule_target.type:
        class: Netgen\BlockManager\View\Matcher\RuleTarget\Type
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: rule_target\type }

    netgen_block_manager.view.matcher.rule_condition.type:
        class: Netgen\BlockManager\View\Matcher\RuleCondition\Type
        tags:
            - { name: netgen_block_manager.view.template_matcher, identifier: rule_condition\type }
