nglayouts_admin:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    methods: [GET]
    defaults:
        route: nglayouts_admin_layout_resolver_index
        permanent: true

nglayouts_admin_layout_resolver_root:
    path: /admin/mappings
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    methods: [GET]
    defaults:
        route: nglayouts_admin_layout_resolver_index
        permanent: true

nglayouts_admin_layouts_root:
    path: /admin/layouts
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    methods: [GET]
    defaults:
        route: nglayouts_admin_layouts_index
        permanent: true

nglayouts_admin_shared_layouts_root:
    path: /admin/shared_layouts
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    methods: [GET]
    defaults:
        route: nglayouts_admin_shared_layouts_index
        permanent: true

nglayouts_admin_transfer_root:
    path: /admin/transfer
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    methods: [GET]
    defaults:
        route: nglayouts_admin_transfer_index
        permanent: true
