services:
    # Admin controllers

    netgen_block_manager.controller.admin.base:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Controller
        public: false
        abstract: true
        parent: netgen_block_manager.controller.base

    ## Layout resolver controllers

    netgen_block_manager.controller.admin.layout_resolver.priorities_validator:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\Utils\PrioritiesValidator
        public: false
        calls:
            - [setValidator, ["@validator"]]

    netgen_block_manager.controller.admin.layout_resolver.index:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\Index
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.create_rule:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\CreateRule
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.update_rule_priorities:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\UpdateRulePriorities
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - "@netgen_block_manager.controller.admin.layout_resolver.priorities_validator"

    netgen_block_manager.controller.admin.layout_resolver.update_rule:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\UpdateRule
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.admin.layout_resolver.enable_rule:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\EnableRule
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.disable_rule:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\DisableRule
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.create_rule_draft:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\CreateRuleDraft
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.discard_rule_draft:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\DiscardRuleDraft
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.publish_rule_draft:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\PublishRuleDraft
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.delete_rule:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\DeleteRule
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.create_target_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\CreateTargetForm
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - "@netgen_block_manager.layout.resolver.registry.target_type"

    netgen_block_manager.controller.admin.layout_resolver.edit_target_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\EditTargetForm
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.delete_target:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\DeleteTarget
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.create_condition_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\CreateConditionForm
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"
            - "@netgen_block_manager.layout.resolver.registry.condition_type"

    netgen_block_manager.controller.admin.layout_resolver.edit_condition_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\EditConditionForm
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    netgen_block_manager.controller.admin.layout_resolver.delete_condition:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\LayoutResolver\DeleteCondition
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout_resolver"

    ## Layouts controllers

    netgen_block_manager.controller.admin.layouts.index:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Layouts\Index
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.admin.layouts.copy_layout_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Layouts\CopyLayoutForm
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.admin.layouts.export_layouts:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Layouts\ExportLayouts
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.transfer.serializer"

    netgen_block_manager.controller.admin.layouts.delete_layout:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Layouts\DeleteLayout
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.admin.layouts.clear_layout_cache:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\Layouts\ClearLayoutCache
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.http_cache.client"

    ## Shared layouts controllers

    netgen_block_manager.controller.admin.shared_layouts.index:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\SharedLayouts\Index
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    netgen_block_manager.controller.admin.shared_layouts.clear_related_layouts_cache:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\Admin\SharedLayouts\ClearRelatedLayoutsCache
        public: true
        parent: netgen_block_manager.controller.admin.base
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.http_cache.client"

    # App controllers

    netgen_block_manager.controller.app.base:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Controller
        public: false
        abstract: true
        parent: netgen_block_manager.controller.base

    ## Index controller

    netgen_block_manager.controller.app.index:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Index
        public: true
        parent: netgen_block_manager.controller.app.base

    ## Layout controllers

    netgen_block_manager.controller.app.layout.create_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Layout\CreateForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.layout"
            - "@netgen_block_manager.locale.provider"

    netgen_block_manager.controller.app.layout.edit_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Layout\EditForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.layout"

    ## Block controllers

    netgen_block_manager.controller.app.block.edit:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Block\Edit
        public: true
        parent: netgen_block_manager.controller.app.base

    netgen_block_manager.controller.app.block.edit_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Block\EditForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.block"

    netgen_block_manager.controller.app.block.edit_config_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Block\EditConfigForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.block"

    ## Collection controllers

    netgen_block_manager.controller.app.collection.edit_collection_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Collection\EditCollectionForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.collection"

    netgen_block_manager.controller.app.collection.edit_item_config_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Collection\EditItemConfigForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.collection"

    netgen_block_manager.controller.app.collection.edit_query_form:
        class: Netgen\Bundle\BlockManagerAdminBundle\Controller\App\Collection\EditQueryForm
        public: true
        parent: netgen_block_manager.controller.app.base
        arguments:
            - "@netgen_block_manager.api.service.collection"
