default_view_templates:
    block_view:
        app: '@nglayouts_admin/app/block/block.html.twig'
    item_view:
        app: '@NetgenLayoutsAdmin/app/item/invalid_item.html.twig'
    layout_view:
        admin: '@NetgenLayoutsAdmin/admin/layouts/layout.html.twig'
    rule_view:
        admin: '@NetgenLayoutsAdmin/admin/layout_resolver/rule.html.twig'
    rule_target_view:
        admin: '@NetgenLayoutsAdmin/admin/layout_resolver/target/target.html.twig'
        value: '@NetgenLayoutsAdmin/admin/layout_resolver/target/value/target.html.twig'
    rule_condition_view:
        value: '@NetgenLayoutsAdmin/admin/layout_resolver/condition/value/condition.html.twig'
