view:
    form_view:
        app:
            layout\create:
                template: "@NetgenLayoutsAdmin/app/form/layout/create.html.twig"
                match:
                    form\type: Netgen\Layouts\Layout\Form\CreateType
            layout\edit:
                template: "@NetgenLayoutsAdmin/app/form/layout/edit.html.twig"
                match:
                    form\type: Netgen\Layouts\Layout\Form\EditType
            block\full_edit:
                template: "@NetgenLayoutsAdmin/app/form/block/edit/full.html.twig"
                match:
                    form\type: Netgen\Layouts\Block\Form\FullEditType
            block\content_edit:
                template: "@NetgenLayoutsAdmin/app/form/block/edit/content.html.twig"
                match:
                    form\type: Netgen\Layouts\Block\Form\ContentEditType
            block\design_edit:
                template: "@NetgenLayoutsAdmin/app/form/block/edit/design.html.twig"
                match:
                    form\type: Netgen\Layouts\Block\Form\DesignEditType
            collection\full_edit:
                template: "@NetgenLayoutsAdmin/app/form/collection/edit/full.html.twig"
                match:
                    form\type: Netgen\Layouts\Collection\Form\CollectionEditType
            query\full_edit:
                template: "@NetgenLayoutsAdmin/app/form/query/edit/full.html.twig"
                match:
                    form\type: Netgen\Layouts\Collection\Form\QueryEditType
            item\view_type_edit:
                template: "@NetgenLayoutsAdmin/app/form/item/edit/view_type.html.twig"
                match:
                    form\type: Netgen\Layouts\Collection\Form\ItemViewTypeEditType
            slot\view_type_edit:
                template: "@NetgenLayoutsAdmin/app/form/slot/edit/view_type.html.twig"
                match:
                    form\type: Netgen\Layouts\Collection\Form\SlotViewTypeEditType
        admin:
            layout\copy:
                template: "@NetgenLayoutsAdmin/admin/layouts/form/copy_layout.html.twig"
                match:
                    form\type: Netgen\Layouts\Layout\Form\CopyType
            shared_layout\related_layouts_cache:
                template: "@NetgenLayoutsAdmin/admin/shared_layouts/form/clear_related_layouts_cache.html.twig"
                match:
                    form\type: Netgen\Bundle\LayoutsAdminBundle\Form\Admin\Type\ClearLayoutsCacheType
            rule\edit:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/form/edit_rule.html.twig"
                match:
                    form\type: Netgen\Layouts\Layout\Resolver\Form\RuleType
            rule\copy:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/form/copy_rule.html.twig"
                match:
                    form\type: Netgen\Bundle\LayoutsAdminBundle\Form\Admin\Type\CopyRuleType
            condition\edit:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/form/edit_condition.html.twig"
                match:
                    form\type: Netgen\Layouts\Layout\Resolver\Form\ConditionType
            target\edit:
                template: "@NetgenLayoutsAdmin/admin/layout_resolver/form/edit_target.html.twig"
                match:
                    form\type: Netgen\Layouts\Layout\Resolver\Form\TargetType
