block_types:
    grid:
        name: 'Grid'
        definition_identifier: list
        defaults:
            view_type: grid
            parameters:
                number_of_columns: 3

    # All gallery blocks are specified via view type specific config
    # so we disable the one which is automatically created
    gallery:
        enabled: false

    slider:
        name: 'Slider'
        definition_identifier: gallery

    thumb_gallery:
        name: 'Thumb gallery'
        definition_identifier: gallery
        defaults:
            view_type: thumb_gallery

    grid_gallery:
        name: 'Grid gallery'
        definition_identifier: gallery
        defaults:
            view_type: grid_gallery

    sushi_bar:
        name: 'Sushi bar'
        definition_identifier: gallery
        defaults:
            view_type: sushi_bar
