block_type_groups:
    basic:
        name: 'Basic'
        block_types: [title, text, button, rich_text, external_video, map, html_snippet]
    listing:
        name: 'Listing'
        block_types: [list, grid]
    gallery:
        name: 'Gallery'
        block_types: [slider, thumb_gallery, grid_gallery, sushi_bar]
    containers:
        name: 'Containers'
        block_types:
            - div_container
            - two_columns_container
    placeholders:
        name: 'Placeholders'
        block_types: [twig_block, full_view]
    custom:
        name: 'Custom blocks'
