layout_types:
    layout_1:
        name: 'Layout 1'
        icon: '/bundles/netgenblockmanager/images/layout_types/layout_1.svg'
        zones:
            main:
                name: 'Main'

    layout_2:
        name: 'Layout 2'
        icon: '/bundles/netgenblockmanager/images/layout_types/layout_2.svg'
        zones:
            header:
                name: 'Header'
            post_header:
                name: 'Post header'
            main:
                name: 'Main'
            pre_footer:
                name: 'Pre footer'
            footer:
                name: 'Footer'

    layout_3:
        name: 'Layout 3'
        icon: '/bundles/netgenblockmanager/images/layout_types/layout_3.svg'
        zones:
            header:
                name: 'Header'
            post_header:
                name: 'Post header'
            left:
                name: 'Left'
            right:
                name: 'Right'
            pre_footer:
                name: 'Pre footer'
            footer:
                name: 'Footer'

    layout_4:
        name: 'Layout 4'
        icon: '/bundles/netgenblockmanager/images/layout_types/layout_4.svg'
        zones:
            header:
                name: 'Header'
            post_header:
                name: 'Post header'
            left:
                name: 'Left'
            right:
                name: 'Right'
            pre_footer:
                name: 'Pre footer'
            footer:
                name: 'Footer'

    layout_5:
        name: 'Layout 5'
        icon: '/bundles/netgenblockmanager/images/layout_types/layout_5.svg'
        zones:
            header:
                name: 'Header'
            post_header:
                name: 'Post header'
            left:
                name: 'Left'
            right:
                name: 'Right'
            pre_footer:
                name: 'Pre footer'
            footer:
                name: 'Footer'

    layout_6:
        name: 'Layout 6'
        icon: '/bundles/netgenblockmanager/images/layout_types/layout_6.svg'
        zones:
            header:
                name: 'Header'
            post_header:
                name: 'Post header'
            top:
                name: 'Top'
            left:
                name: 'Left'
            center:
                name: 'Center'
            right:
                name: 'Right'
            pre_footer:
                name: 'Pre footer'
            footer:
                name: 'Footer'
