services:
    netgen_block_manager.layout.resolver.target_handler.doctrine.route:
        class: Netgen\BlockManager\Layout\Resolver\TargetHandler\Doctrine\Route
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: route }

    netgen_block_manager.layout.resolver.target_handler.doctrine.route_prefix:
        class: Netgen\BlockManager\Layout\Resolver\TargetHandler\Doctrine\RoutePrefix
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: route_prefix }

    netgen_block_manager.layout.resolver.target_handler.doctrine.path_info:
        class: Netgen\BlockManager\Layout\Resolver\TargetHandler\Doctrine\Route
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: path_info }

    netgen_block_manager.layout.resolver.target_handler.doctrine.path_info_prefix:
        class: Netgen\BlockManager\Layout\Resolver\TargetHandler\Doctrine\RoutePrefix
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: path_info_prefix }

    netgen_block_manager.layout.resolver.target_handler.doctrine.request_uri:
        class: Netgen\BlockManager\Layout\Resolver\TargetHandler\Doctrine\Route
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: request_uri }

    netgen_block_manager.layout.resolver.target_handler.doctrine.request_uri_prefix:
        class: Netgen\BlockManager\Layout\Resolver\TargetHandler\Doctrine\RoutePrefix
        public: false
        tags:
            - { name: netgen_block_manager.layout.resolver.target_handler.doctrine, target_type: request_uri_prefix }
