parameters:
    netgen_layouts.app.csrf_token_id: nglayouts_app
    netgen_layouts.app.pagelayout: '@@NetgenLayoutsAdmin/app/pagelayout.html.twig'
    netgen_layouts.app.automatic_cache_clear: true
    netgen_layouts.admin.csrf_token_id: nglayouts_admin
    netgen_layouts.admin.pagelayout: '@@NetgenLayoutsAdmin/admin/pagelayout.html.twig'
