services:
    netgen_layouts.command.export:
        class: Netgen\Bundle\LayoutsBundle\Command\ExportCommand
        arguments:
            - "@netgen_layouts.transfer.serializer"
        tags:
            - { name: console.command, command: nglayouts:export }

    netgen_layouts.command.import:
        class: Netgen\Bundle\LayoutsBundle\Command\ImportCommand
        arguments:
            - "@netgen_layouts.transfer.importer"
        tags:
            - { name: console.command, command: nglayouts:import }
