services:
    netgen_block_manager.layout.form.create:
        class: Netgen\Layouts\Layout\Form\CreateType
        arguments:
            - "@netgen_block_manager.layout.registry.layout_type"
        tags:
            - { name: form.type }
