services:
    netgen_layouts.item.item_builder:
        class: Netgen\Layouts\Item\CmsItemBuilder
        arguments:
            - !tagged_iterator netgen_layouts.cms_value_converter

    netgen_layouts.item.item_loader:
        class: Netgen\Layouts\Item\CmsItemLoader
        arguments:
            - "@netgen_layouts.item.item_builder"
            - !tagged_locator { tag: netgen_layouts.cms_value_loader, index_by: value_type }

    netgen_layouts.item.url_generator:
        class: Netgen\Layouts\Item\UrlGenerator
        arguments:
            - !tagged_locator { tag: netgen_layouts.cms_value_url_generator, index_by: value_type }

    netgen_layouts.item.registry.value_type:
        class: Netgen\Layouts\Item\Registry\ValueTypeRegistry
        arguments:
            - !abstract "Set in ValueTypePass"

    netgen_layouts.item.value_loader.null:
        class: Netgen\Layouts\Item\ValueLoader\NullValueLoader
        tags:
            - { name: netgen_layouts.cms_value_loader, value_type: "null" }
